// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-KAvPToxD_F736aP2qPiSm9FgVhDTylE',
    appId: '1:397033897058:web:adbc61a8e550d686bc653b',
    messagingSenderId: '397033897058',
    projectId: 'expense-calculator-649ae',
    authDomain: 'expense-calculator-649ae.firebaseapp.com',
    storageBucket: 'expense-calculator-649ae.firebasestorage.app',
    measurementId: 'G-K5G6GXZ0FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6d7EZUgUiK_jpmiR7Z9od9xMOECuqWdA',
    appId: '1:397033897058:android:e7065313dc8703cabc653b',
    messagingSenderId: '397033897058',
    projectId: 'expense-calculator-649ae',
    storageBucket: 'expense-calculator-649ae.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-KAvPToxD_F736aP2qPiSm9FgVhDTylE',
    appId: '1:397033897058:web:25e24227df2ee445bc653b',
    messagingSenderId: '397033897058',
    projectId: 'expense-calculator-649ae',
    authDomain: 'expense-calculator-649ae.firebaseapp.com',
    storageBucket: 'expense-calculator-649ae.firebasestorage.app',
    measurementId: 'G-SD6N7XX1X0',
  );

}